swc-installation-test-2.py: Leave close_fds ambigious in Popen()
MS Windows can choke with:

  ValueError: close_fds is not supported on Windows platforms if you
  redirect stdin/stdout/stderr

We shouldn't have any other file descriptors open, so we'll stick with
the Popen default (which may depend on your system [1]).

[1]: http://docs.python.org/3.3/library/subprocess.html#subprocess.Popen