compile.py: use keys instead of cmp for sorting
cmp is gone in Python 3.

I use the tuple (x._sort_key, id(x)) instead of just x._sort_key to
avoid

  Traceback (most recent call last):
    ...
    File "bin/compile.py", line 248, in _load_subfiles
      self.children.sort(key=lambda x: x._sort_key)
  TypeError: unorderable types: NoneType() < NoneType()

which happens when multiple children have _sort_key == None.  Breaking
these ties based on the child's id is random, but it works.  If you
want a predictable tie breaker, fix _sort_key ;).